apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: flakey
data:
  FAILURE_RATE: '0'
  REDIS_URL: 'redis://redis.flakey:6379/0'
  VERSION: '9'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-migrate
  namespace: flakey
data:
  REDIS_URL: 'redis://redis.flakey:6379/0'
  VERSION: '9'
