apiVersion: v1
kind: ConfigMap
metadata:
  name: 'config${config_suffix}'
  namespace: flakey
  labels:
    stage: '${service_stage}'
data:
  FAILURE_RATE: '50'
  REDIS_URL: 'redis://redis.flakey:6379/0'
  VERSION: '10'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: 'config-migrate${config_suffix}'
  namespace: flakey
  labels:
    stage: '${service_stage}'
data:
  REDIS_URL: 'redis://redis.flakey:6379/0'
  VERSION: '10'
